### ISSUE TITLE
Endianess of RISC-V

### ISSUE THREAD

**Issue by TheThirdOne** [d0iasm/rvemu-for-book#1]
The section explaining why rvemu is little-endian may mislead readers because it is not precise enough.

While the base memory system does not need to be little-endian with regards to instruction decoding, the current standardized memory operations do have to be little-endian. I think this may have been a requirement added after the 1.0 release of the specification, but I don't want to track down when it was added.

From: https://book.rvemu.app/setup-and-implement-two-instructions
> RISC-V has either little-endian or big-endian byte order, but our emulator will implement a little-endian system since it is currently dominant commercially like x86 systems.

Section 1.2 of RISC-V Specification v2.0
> The base RISC-V ISA has a little-endian memory system, but non-standard variants can provide a big-endian or bi-endian memory system

The section goes on to explain the exact (rather complex) memory requirements of the RISC-V.

Section 2.6 of RISC-V Specification v2.0
> RV32I provides a 32-bit user address space that is byte-addressed and little-endian.

**Comment by d0iasm** [comment]
Thank you for pointing it out!

I read these parts from "The RISC-V Instruction Set Manual Volume I: Unprivileged ISA Document Version 20191213":
1.5 Base Instruction-Length Encoding:
> RISC-V base ISAs have either little-endian or big-endian memory systems, with the privileged
architecture further defining bi-endian operation.

2.6 Load and Store Instructions:
> The EEI will define whether the memory system is little-endian or big-endian. In RISC-V, endianness is byte-address invariant.

I think the specification relating to the endianness has changed since v2.0 because "Preface" says:
> • Defined big-endian ISA variant.

If I understand correctly, the standard memory system is little-endian but there is a variant for big-endian.

I'll read the spec carefully again and fix this part to explain it precisely.
Thank you for your comment!

**Comment by TheThirdOne** [comment]
Thank you for including the quotes, they prompted me to download the newest draft and it indeed has support for big endian systems. My knowledge was out of date and I apologize for that.

Given the latest specification allows it I think that the wording in the rvemu book is unlikely to significantly mislead readers.

I think it probably could be a little more nuanced, but I don't think it needs to be fixed.

I hope it was useful rather than a nuisance to you to look at the specification.
